services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: ITransition-Course-Project
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - itransition-network

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"
    networks:
      - itransition-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - itransition-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - itransition-network


volumes:
  mysql-data:

networks:
  itransition-network:
    driver: bridge
